// Wrapper script generation. The wrapper is a thin, self-contained script:
// it knows the absolute paths of the real kimi, the JS entry and the node
// executable recorded at install time, so it never scans PATH itself (which
// would recurse into the wrapper).
import { chmod, mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

export const WRAPPER_MARKER = 'open-kimi-web integration wrapper';

/** Quote a literal for POSIX sh single-quoted strings. */
function shQuote(value) {
  return `'${value.replaceAll("'", "'\\''")}'`;
}

export function renderShWrapper({ entry, realKimi, node }) {
  return `#!/bin/sh
# ${WRAPPER_MARKER} — generated by \`open-kimi-web integrate install\`.
# Do not edit; regenerate with \`open-kimi-web integrate repair\`.
OPEN_KIMI_REAL_KIMI=${shQuote(realKimi)}
export OPEN_KIMI_REAL_KIMI
if [ -x ${shQuote(node)} ]; then
  exec ${shQuote(node)} ${shQuote(entry)} __wrap "$@"
elif command -v node >/dev/null 2>&1; then
  exec node ${shQuote(entry)} __wrap "$@"
else
  echo "open-kimi-web wrapper: node executable not found; run: open-kimi-web integrate repair" >&2
  exit 127
fi
`;
}

export function renderCmdWrapper({ entry, realKimi, node }) {
  return `@echo off
rem ${WRAPPER_MARKER} — generated by "open-kimi-web integrate install".
rem Do not edit; regenerate with "open-kimi-web integrate repair".
set "OPEN_KIMI_REAL_KIMI=${realKimi}"
if exist "${node}" goto recorded
where node >nul 2>nul
if errorlevel 1 goto nonode
node "${entry}" __wrap %*
exit /b %ERRORLEVEL%
:recorded
"${node}" "${entry}" __wrap %*
exit /b %ERRORLEVEL%
:nonode
echo open-kimi-web wrapper: node executable not found; run: open-kimi-web integrate repair 1>&2
exit /b 127
`;
}

/** sh launcher: plain `open-kimi-web` command (no wrapping, no real kimi). */
export function renderShLauncher({ entry, node }) {
  return `#!/bin/sh
# ${WRAPPER_MARKER} — generated by \`open-kimi-web integrate install\`.
# Do not edit; regenerate with \`open-kimi-web integrate repair\`.
if [ -x ${shQuote(node)} ]; then
  exec ${shQuote(node)} ${shQuote(entry)} "$@"
elif command -v node >/dev/null 2>&1; then
  exec node ${shQuote(entry)} "$@"
else
  echo "open-kimi-web launcher: node executable not found; run: open-kimi-web integrate repair" >&2
  exit 127
fi
`;
}

/** cmd launcher: plain `open-kimi-web` command (no wrapping, no real kimi). */
export function renderCmdLauncher({ entry, node }) {
  return `@echo off
rem ${WRAPPER_MARKER} — generated by "open-kimi-web integrate install".
rem Do not edit; regenerate with "open-kimi-web integrate repair".
if exist "${node}" goto recorded
where node >nul 2>nul
if errorlevel 1 goto nonode
node "${entry}" %*
exit /b %ERRORLEVEL%
:recorded
"${node}" "${entry}" %*
exit /b %ERRORLEVEL%
:nonode
echo open-kimi-web launcher: node executable not found; run: open-kimi-web integrate repair 1>&2
exit /b 127
`;
}

export function wrapperFileNames(platform) {
  return platform === 'win32' ? ['kimi.cmd', 'open-kimi-web.cmd'] : ['kimi', 'open-kimi-web'];
}

function isKimiWrapperName(name) {
  return name === 'kimi' || name === 'kimi.cmd';
}

function renderFile(platform, context, name) {
  if (platform === 'win32') {
    return isKimiWrapperName(name) ? renderCmdWrapper(context) : renderCmdLauncher(context);
  }
  return isKimiWrapperName(name) ? renderShWrapper(context) : renderShLauncher(context);
}

export async function writeWrappers(binDir, platform, context) {
  await mkdir(binDir, { recursive: true });
  const files = [];
  for (const name of wrapperFileNames(platform)) {
    const path = join(binDir, name);
    const rendered = renderFile(platform, context, name);
    // cmd.exe mis-parses LF-only batch files (labels and lines get mangled).
    const content = platform === 'win32' ? rendered.replaceAll('\n', '\r\n') : rendered;
    await writeFile(path, content, { mode: 0o755 });
    if (platform !== 'win32') await chmod(path, 0o755);
    files.push(path);
  }
  return files;
}

/** A wrapper file is "ours" only when it carries the generation marker. */
export async function isOurWrapper(path) {
  try {
    return (await readFile(path, 'utf8')).includes(WRAPPER_MARKER);
  } catch {
    return false;
  }
}
